### PR TITLE
Fix coverage

### PR DESCRIPTION
**Pull request by didierdemoniere**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...) 
fix

* **What is the current behavior?** (You can also link to an open issue here)
nyc ignore .ts files

* **What is the new behavior (if this is a feature change)?**

* **Other information**:

### CODE REVIEW

**Comment by bitjson** [comment]
Hey @didierdemoniere thanks for opening a PR! I can't seem to reproduce the issue – the `extension` settings should already be automatically set by the [extends: `@istanbuljs/nyc-config-typescript` in package.json](https://github.com/bitjson/typescript-starter/blob/65f82a9094421f74db887ebafd7b417bb1fc0ada/package.json#L133):
```
{
  "cache": false,
  "extension": [
    ".ts",
    ".tsx"
  ],
  "exclude": [
    "**/*.d.ts",
    "coverage/**",
    "packages/*/test/**",
    "test/**",
    "test{,-*}.ts",
    "**/*{.,-}{test,spec}.ts",
    "**/__tests__/**",
    "**/node_modules/**"
  ]
}
```
If you create a new project, do you still see the issue?

**Comment by mrGibi** [comment]
I had to manually install `@istanbuljs/nyc-config-typescript`.

**Comment by didierdemoniere** [comment]
Hi @bitjson, to reproduce this i run: `npx typescript-starter` then `npm run cov` inside the project.
is `@istanbuljs/nyc-config-typescript` installed globally on your setup ?

**Comment by bitjson** [comment]
@didierdemoniere thanks for responding! (And thank you to @mrGibi too.) You were right – the package was being removed on install by the CLI. I credited you in https://github.com/bitjson/typescript-starter/commit/710bf3e871ee162f3f7bdbfb1438c9b6130562e1, released as [v2.4.7](https://github.com/bitjson/typescript-starter/commit/5a9412b0a6fb08a5151cb6ffd8a3e84fdac178c8).

**Comment by didierdemoniere** [comment]
thanks @bitjson. This package is a huge time saver, keep up the good work.

**Pull request closed without merging**
