### PR TITLE
Add copy/paste detector to scripts in package.json

### PR DESCRIPTION
**Pull request by kucherenko**
What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)
feature

What is the current behavior? (You can also link to an open issue here)
no copy/paste detection

What is the new behavior (if this is a feature change)?
add copy/paste detector for typescript-starter

Other information:

### CODE REVIEW

**Comment by bitjson** [comment]
Hey @kucherenko, thanks for the PR! 

The goal here is to provide a very minimal "good" setup, and then optionally provide plenty of other "Extras" like Travis or Yarn. Could you add this as an option? Just needs to be configured in a few places. See the Travis option for an example:

https://github.com/bitjson/typescript-starter/blob/8eaf9636c6cfbd9b1b5c0b4393c32f35f06e8d7d/src/cli/inquire.ts#L121-L125

https://github.com/bitjson/typescript-starter/blob/8eaf9636c6cfbd9b1b5c0b4393c32f35f06e8d7d/src/cli/args.ts#L22-L23

And here's the spot where the magic happens:
https://github.com/bitjson/typescript-starter/blob/8eaf9636c6cfbd9b1b5c0b4393c32f35f06e8d7d/src/cli/typescript-starter.ts#L90

So we just need to add this new package to that list if the user enabled the option.

**Comment by kucherenko** [comment]
@bitjson thank you for comment, fixed

**Comment by kucherenko** [comment]
@bitjson may I ask your help, looks like appveyor didn't use last changes, could you please restart the build on appveyor?

**Comment by bitjson** [comment]
Hey @kucherenko, sorry to keep you waiting here. If you're still interested in adding this, could you fix the merge conflicts? 

(I'm going to close this for now just to clean up issues, but feel free to re-open if you still want to work on it!)

**Pull request closed without merging**
